name: Voice Conversations Data Sync

on:
  schedule:
    # Run every 12 hours at 1pm and 1am EST (6pm and 6am UTC)
    - cron: '0 18,6 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-voice-conversations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv sqlalchemy psycopg2-binary
        
    - name: Set up database connection
      run: |
        echo "Setting up direct database connection..."
        echo "Database host: wsprod-pantheon-redshift-c9qtpydth0xz.ws1.us-east-1.a.p1.satoricyber.net"
        echo "Port: 12345"
        echo "Database: pantheon"
        
    - name: Set up environment variables
      run: |
        # Set up environment variables for direct database connection
        echo "SATORI_USERNAME=${{ secrets.SATORI_USERNAME }}" >> $GITHUB_ENV
        echo "SATORI_PASSWORD=${{ secrets.SATORI_PASSWORD }}" >> $GITHUB_ENV
        echo "WORKATO_WEBHOOK_URL=${{ secrets.WORKATO_WEBHOOK_URL }}" >> $GITHUB_ENV
        
    - name: Run voice conversations script
      run: |
        echo "Starting script execution..."
        echo "Current directory: $(pwd)"
        echo "Changing to decagon_voice directory..."
        cd decagon_voice
        echo "New directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Checking Python version..."
        python3 --version
        echo "Checking if script file exists..."
        ls -la voice_conversations_warehouse_clean.py
        echo "Running Python script..."
        python3 voice_conversations_warehouse_clean.py
        echo "Script completed with exit code: $?"
        echo "Checking if JSON file was created..."
        ls -la *.json || echo "No JSON files found"
        
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: voice-conversations-results
        path: decagon_voice/voice_conversations_warehouse.json
        retention-days: 7
